default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tvtracker_development
  username: postgres
  password: admin

test:
  <<: *default
  database: tvtracker_test
  username: postgres
  password: admin

production:
  <<: *default
  database: dek8d6julafjmv
  username: ppiswzggcpieho
  password: 4b9fba9039f0822713b49bd13130acd609d099fc086fa1617d45259452b05445
  port: 5432
  url: postgres://ppiswzggcpieho:4b9fba9039f0822713b49bd13130acd609d099fc086fa1617d45259452b05445@ec2-54-246-87-132.eu-west-1.compute.amazonaws.com:5432/dek8d6julafjmv
